// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ME_SimpleTimeSystem","status":false,"description":"This is a plugin for ingame time","parameters":{"lengthS":"1","secondsDuration":"60","minutesDuration":"60","hoursDuration":"24","daysDuration":"30","monthsDuration":"12","day":"1","month":"1","year":"1","hour":"6","minute":"0","second":"0"}},
{"name":"ME_CustomSTSDefaultMenu","status":false,"description":"Allows you to see ME_SimpleTimeSystem on your scene Menu","parameters":{}}
];
